// Contenido de las tres landings. Cada afirmación sobre lo que hace el
// sistema está registrada en ../demos/AFIRMACIONES.md con su evidencia.
export const COMUN = {
  proceso: [
    ['Diagnóstico de 30 minutos', 'Por videollamada. Nos cuentas el proceso, te enseñamos el sistema funcionando y te decimos qué construiríamos. Si no encaja, te lo decimos.'],
    ['Propuesta concreta', 'Qué problema resuelve, qué sistema, qué incluye, cuánto se paga al principio y cuánto después (solo si hay trabajo recurrente real).'],
    ['Construcción sobre vuestros datos', 'Sobre vuestra forma real de trabajar y conectado a lo que ya usáis.'],
    ['Medición', 'Comprobamos con datos si hace lo que tenía que hacer.'],
  ],
  catalogo: [
    ['Seguimiento de solicitudes y presupuestos', 'CRM, borrador de propuesta y recordatorio de seguimiento.'],
    ['Consultas de clientes', 'Cada email se convierte en un ticket con prioridad, responsable y plazo.'],
    ['Proyectos y tareas', 'Al ganar un cliente se crea el proyecto, se reparten tareas por carga y se vigilan plazos.'],
    ['Automatizaciones concretas', 'Recordatorios, copias de seguridad, encuestas a clientes.'],
    ['Auditoría de tu web', 'Revisión de la web y recomendaciones de mejora.'],
  ],
  faqComun: [
    ['¿Qué pasa en el diagnóstico?', '30 minutos por videollamada. Nos cuentas cómo trabajáis, te enseñamos el sistema funcionando y te decimos qué construiríamos y por dónde empezaríamos. Si no es para vosotros, te lo decimos.'],
    ['¿Tengo que cambiar de programas?', 'No necesariamente. Conectamos lo que ya usáis siempre que tenga forma de conectarse; si algo no se puede, te lo decimos en el diagnóstico.'],
    ['¿Vendéis paquetes cerrados?', 'No. Cada propuesta dice qué problema resuelve, qué incluye y cuánto se paga al principio y después. Solo hay cuota mensual si hay trabajo recurrente real (mantenimiento, soporte, supervisión).'],
    ['¿Qué datos usa la demo?', 'Inventados. Ninguna empresa, persona ni importe de la demo es real. En el diagnóstico te enseñamos el sistema real.'],
  ],
};

export const LANDINGS = [
  {
    slug: 'automatizacion-procesos',
    demo: 'procesos',
    grupo: 'GA1',
    title: 'Automatización de procesos para empresas | D-Code Partners',
    description: 'Elegimos contigo el proceso que más tiempo os quita, construimos el sistema que lo hace y lo conectamos con vuestras herramientas. Mira la demo.',
    kicker: 'Automatización de procesos',
    h1: 'Los pasos que repetís cada día, <em>hechos por un sistema</em>',
    sub: 'Elegimos contigo el proceso que más tiempo os quita, construimos el sistema que lo hace y lo conectamos con las herramientas que ya usáis.',
    pasos: ['Vemos qué pasos se repiten siempre igual', 'Construimos el sistema que los hace', 'Lo ves funcionando antes de decidir nada'],
    problemaTitulo: 'Si esto os pasa, es por donde se empieza',
    problemas: [
      ['Copiar los mismos datos de un sitio a otro', 'Del formulario a la hoja, de la hoja al correo, del correo al calendario.'],
      ['Tareas que dependen de que alguien se acuerde', 'Crear la carpeta, avisar al equipo, revisar un plazo.'],
      ['Nadie ve en qué punto está cada cosa', 'Hay que preguntar para saber qué está hecho y qué falta.'],
    ],
    sistemaTitulo: 'Qué construye D-Code',
    sistemaLead: 'Un sistema que hace los pasos repetitivos y deja a las personas lo que requiere criterio.',
    flujo: [
      ['Entra algo', 'Una solicitud, un email, una propuesta aceptada.'],
      ['Se registra solo', 'Los datos van donde tienen que ir, sin copiarlos a mano.'],
      ['Se actúa', 'Se crean tareas, se asignan y se envían los avisos.'],
      ['Se sigue', 'Se ve qué está hecho y qué toca, y se avisa antes de un retraso.'],
    ],
    sistemaHace: ['Copiar y registrar datos', 'Crear proyectos y tareas', 'Repartir tareas con reglas', 'Avisar de plazos y retrasos'],
    personaDecide: ['El alcance de cada trabajo', 'Precios y condiciones', 'Excepciones', 'El trato con el cliente'],
    faq: [],
  },
  {
    slug: 'automatizacion-seguimiento-comercial',
    demo: 'comercial',
    grupo: 'GA2',
    title: 'Automatizar el seguimiento de clientes y presupuestos | D-Code Partners',
    description: 'Cada solicitud entra sola en el CRM, la propuesta se prepara como borrador y el sistema avisa cuando toca hacer seguimiento. Mira la demo.',
    kicker: 'Seguimiento comercial',
    h1: 'Que ningún presupuesto <em>se quede sin seguimiento</em>',
    sub: 'Construimos el sistema que registra cada solicitud, prepara la propuesta para que una persona la revise y avisa cuando toca hacer seguimiento.',
    pasos: ['Cada solicitud entra sola en un CRM, con su origen', 'La propuesta se prepara como borrador y la revisa una persona', 'Si no hay respuesta, el responsable recibe un aviso'],
    problemaTitulo: '¿Os suena?',
    problemas: [
      ['Presupuestos enviados que nadie vuelve a mirar', 'Se envían y se olvidan hasta que el cliente ya ha elegido a otro.'],
      ['Solicitudes repartidas en varios sitios', 'Web, email y teléfono, cada una en un lugar distinto.'],
      ['No sabes qué oportunidades siguen abiertas', 'Para saberlo hay que revisar correos o preguntar.'],
    ],
    sistemaTitulo: 'Qué construye D-Code',
    sistemaLead: 'El núcleo del sistema comercial: CRM, borrador de propuesta y recordatorio de seguimiento.',
    flujo: [
      ['Solicitud', 'Entra por la web o por email.'],
      ['CRM', 'Se registra sola, con su origen y su siguiente paso.'],
      ['Borrador de propuesta', 'El sistema lo prepara con los datos del CRM.'],
      ['Revisión y envío', 'Una persona revisa la propuesta y la envía.'],
      ['Recordatorio', 'Si no hay respuesta, el responsable recibe un aviso.'],
    ],
    sistemaHace: ['Registrar cada solicitud con su origen', 'Preparar el borrador de propuesta', 'Recordar el seguimiento', 'Mostrar qué está abierto'],
    personaDecide: ['Qué se ofrece y a qué precio', 'Revisar y enviar la propuesta', 'Cómo y cuándo llamar', 'Cerrar la venta'],
    faq: [['¿La propuesta se envía sola?', 'No. El sistema prepara un borrador; una persona lo revisa y decide cuándo enviarlo.']],
  },
  {
    slug: 'automatizacion-atencion-clientes',
    demo: 'atencion',
    grupo: 'GA3',
    title: 'Automatizar la atención de consultas de clientes | D-Code Partners',
    description: 'Cada email de cliente se convierte en un ticket con prioridad, se asigna a quien tiene menos carga y se avisa antes de que venza el plazo. Mira la demo.',
    kicker: 'Consultas de clientes',
    h1: 'Cada consulta de cliente, <em>con prioridad y responsable</em>',
    sub: 'Construimos el sistema que convierte cada email de cliente en un ticket con prioridad, lo asigna a quien tiene menos carga y avisa antes de que venza el plazo.',
    pasos: ['Cada email de cliente se convierte en un ticket', 'Se asigna a quien tiene menos carga', 'Aviso antes del plazo y escalado si se incumple'],
    problemaTitulo: '¿Os suena?',
    problemas: [
      ['Un buzón compartido donde se pierden emails', 'Lo que no se responde hoy se queda abajo.'],
      ['Nadie sabe quién lleva cada consulta', 'Dos personas contestan lo mismo o nadie contesta.'],
      ['Lo urgente se sabe tarde', 'Cuando el cliente vuelve a escribir, ya enfadado.'],
    ],
    sistemaTitulo: 'Qué construye D-Code',
    sistemaLead: 'No es un chatbot: es el sistema que ordena las consultas que ya os llegan.',
    flujo: [
      ['Email de cliente', 'Llega al buzón de siempre.'],
      ['Ticket', 'Si es una consulta, se crea un ticket con prioridad. Si no lo es, no.'],
      ['Responsable', 'Se asigna a quien tiene menos carga en ese momento.'],
      ['Plazo', 'Aviso al responsable antes de que venza.'],
      ['Escalado', 'Si se incumple, se avisa a dirección.'],
    ],
    sistemaHace: ['Separar consultas de lo que no lo es', 'Crear el ticket con prioridad', 'Asignar por carga', 'Vigilar plazos y escalar'],
    personaDecide: ['Qué se responde al cliente', 'Los plazos de cada prioridad', 'Casos especiales', 'Cerrar el ticket'],
    faq: [['¿Responde la IA a los clientes?', 'No en este sistema. Ordena, prioriza y asigna; la respuesta la da una persona del equipo.']],
  },
];
