/*
 * UNA PÁGINA POR CADA COSA QUE HACEMOS.
 *
 * «Qué hacemos» dice las cinco en una línea cada una. Quien quiere saber más
 * pulsa y llega aquí: poco texto, un ejemplo de verdad y algo que se pueda
 * abrir y tocar. Nada de folleto largo.
 *
 * La regla de esta ronda sigue en pie: lo mínimo a la vista. Cada página es
 * un titular, tres o cuatro frases, un ejemplo y una lista de lo que incluye
 * plegada. Todo lo demás —precios, alcance— vive donde ya vivía.
 */

export const FICHAS = [
  {
    id: 'sistemas', slug: 'sistemas-a-medida',
    precio: 'g-medida', fig: 'sistemas',
    t: { es: 'Sistemas a medida', en: 'Custom systems' },
    h: { es: 'Cuando lo que necesitas no se compra hecho.',
         en: 'When what you need cannot be bought ready-made.' },
    lead: { es: 'Miramos cómo trabaja tu empresa de verdad —siguiendo un cliente, un pedido y una factura de principio a fin— y construimos el sistema que hace ese trabajo. No una herramienta más: el sitio por donde pasa todo.',
            en: 'We look at how your company actually works — following a customer, an order and an invoice end to end — and build the system that does that work. Not one more tool: the place everything goes through.' },
    puntos: {
      es: [['Se empieza midiendo', 'Cuántas veces una persona hace de puente entre dos programas. Esa cifra es la que decide qué se construye primero.'],
           ['Alcance y precio antes de tocar nada', 'Por escrito. Si cambia durante el camino, se vuelve a escribir.'],
           ['Por partes', 'La primera pieza funciona en semanas, no en meses. Lo siguiente se decide con ella ya en marcha.'],
           ['Tuyo al terminar', 'El código, los datos y los accesos, a tu nombre. Sin candado.']],
      en: [['It starts with a measurement', 'How many times a person acts as a bridge between two programs. That figure decides what gets built first.'],
           ['Scope and price before anything is touched', 'In writing. If it changes along the way, it gets rewritten.'],
           ['In parts', 'The first piece works in weeks, not months. What comes next is decided with it already running.'],
           ['Yours when it is done', 'The code, the data and the access, in your name. No lock-in.']],
    },
    demo: { tipo: 'demo', ruta: { es: '/#sistemas', en: '/en/#sistemas' },
            t: { es: 'Cuatro sistemas funcionando', en: 'Four systems running' },
            d: { es: 'En la portada hay cuatro que puedes abrir ahora mismo: finanzas, comercial, operaciones y atención. Empresa ficticia, sistema de verdad.',
                 en: 'On the home page there are four you can open right now: finance, sales, operations and support. Made-up company, real system.' } },
  },
  {
    id: 'automatizaciones', slug: 'automatizaciones',
    precio: 'g-automatiza', fig: 'automatizaciones',
    t: { es: 'Automatizaciones', en: 'Automations' },
    h: { es: 'Lo que se repite cada semana deja de hacerse a mano.',
         en: 'What repeats every week stops being done by hand.' },
    lead: { es: 'Una tarea que alguien hace todos los martes pasa a ejecutarse sola, con su control de errores y su aviso cuando algo no sale. Ni magia ni cajas negras: se ve qué hizo, cuándo y con qué datos.',
            en: 'A task someone does every Tuesday starts running on its own, with error handling and an alert when something goes wrong. No magic and no black boxes: you can see what it did, when, and with what data.' },
    puntos: {
      es: [['Una tarea, un proceso o un flujo con IA', 'Desde «cuando entre una factura, guárdala aquí» hasta un proceso entero encadenado.'],
           ['Con tus herramientas', 'Las que ya usáis. No hay que cambiar de programa para automatizar lo que hace ese programa.'],
           ['Avisa cuando se rompe', 'Y se rompe: el día que el otro cambia su API. Por eso el mantenimiento va aparte y se dice.'],
           ['Queda documentado', 'Qué hace, qué toca y cómo apagarlo. Para que no dependa de que nos cojas el teléfono.']],
      en: [['One task, a process, or an AI flow', 'From “when an invoice arrives, file it here” to a whole chained process.'],
           ['With your tools', 'The ones you already use. You do not have to change software to automate what that software does.'],
           ['It warns you when it breaks', 'And it does break: the day someone changes their API. That is why maintenance is separate and stated.'],
           ['It comes documented', 'What it does, what it touches and how to switch it off. So it does not depend on reaching us.']],
    },
    demo: { tipo: 'demo', ruta: { es: '/#sistemas', en: '/en/#sistemas' },
            t: { es: 'Míralo en el sistema comercial', en: 'See it in the sales system' },
            d: { es: 'Una sola bandeja donde la IA lee cada contacto que entra, lo clasifica y lo asigna. Eso es una automatización, y se puede abrir.',
                 en: 'A single inbox where AI reads every incoming contact, sorts it and assigns it. That is an automation, and you can open it.' } },
  },
  {
    id: 'agentes', slug: 'agentes-de-ia',
    precio: 'g-agentes', fig: 'agentes',
    t: { es: 'Chatbots y agentes de IA', en: 'Chatbots and AI agents' },
    h: { es: 'Contestan con tus datos, no con lo que se inventen.',
         en: 'They answer from your data, not from what they make up.' },
    lead: { es: 'Atienden por la web, por WhatsApp o por teléfono, responden con lo que hay en tus sistemas y pasan la conversación a una persona cuando hace falta. Todo lo que dicen queda registrado y se puede revisar.',
            en: 'They answer on the web, on WhatsApp or by phone, reply with what is in your systems and hand the conversation to a person when needed. Everything they say is logged and reviewable.' },
    puntos: {
      es: [['Sin inventar', 'Si la respuesta no está en tus datos, lo dice y escala. Un agente que improvisa cuesta más clientes de los que ahorra.'],
           ['Escala con el contexto entero', 'Quien recoge la conversación ve todo lo anterior, no un «hola, ¿en qué puedo ayudar?».'],
           ['Cuota fija', 'No se paga por conversación. Si se usa mucho, mejor: para eso está.'],
           ['Queda el registro', 'Cada respuesta, con su hora y su fuente. Se puede auditar y se puede corregir.']],
      en: [['No making things up', 'If the answer is not in your data, it says so and escalates. An agent that improvises costs more customers than it saves.'],
           ['It escalates with the full context', 'Whoever picks up the conversation sees everything before it, not a “hello, how can I help?”.'],
           ['Flat fee', 'You do not pay per conversation. If it gets used a lot, all the better: that is the point.'],
           ['The log stays', 'Every answer, with its time and its source. It can be audited and it can be corrected.']],
    },
    demo: { tipo: 'chat',
            t: { es: 'El de esta web, sin ir a ninguna parte', en: 'The one on this site, without going anywhere' },
            d: { es: 'El asistente de abajo a la derecha es uno de estos: responde con lo que dice la web y nada más. Pregúntale algo que no esté escrito y verás qué contesta.',
                 en: 'The assistant at the bottom right is one of these: it answers with what the site says and nothing else. Ask it something that is not written here and see what it replies.' } },
  },
  {
    id: 'integraciones', slug: 'integraciones',
    precio: 'g-integra', fig: 'integraciones',
    t: { es: 'Integraciones', en: 'Integrations' },
    h: { es: 'El dato se escribe una vez y aparece donde tiene que aparecer.',
         en: 'Data is entered once and shows up where it should.' },
    lead: { es: 'Tu CRM, tu ERP, tu web y tus hojas, hablándose. Con los permisos mínimos necesarios, con reintentos cuando el otro lado falla y con rastro de lo que pasó.',
            en: 'Your CRM, your ERP, your site and your spreadsheets, talking to each other. With the minimum permissions needed, with retries when the other side fails and with a trail of what happened.' },
    puntos: {
      es: [['También con el sistema de siempre', 'Ese que nadie quiere tocar. Se lee y se escribe por la vía que admita, sin modificarlo por dentro.'],
           ['Permisos mínimos', 'Una integración no necesita acceso a todo. Se pide lo justo y se deja escrito qué se pidió.'],
           ['Reintentos y rastro', 'Si el otro lado se cae, se reintenta; si sigue cayéndose, avisa. Nada se pierde en silencio.'],
           ['En los dos sentidos si hace falta', 'O en uno solo, que muchas veces es lo correcto y lo más barato.']],
      en: [['Also with your long-standing system', 'The one nobody wants to touch. It is read and written through whatever it supports, without modifying its insides.'],
           ['Minimum permissions', 'An integration does not need access to everything. Only what is needed is requested, and it is written down.'],
           ['Retries and a trail', 'If the other side goes down, it retries; if it keeps going down, it warns you. Nothing is lost silently.'],
           ['Both ways if needed', 'Or just one, which is often the right and cheaper answer.']],
    },
    demo: { tipo: 'demo', ruta: { es: '/sistema-financiero', en: '/en/sistema-financiero' },
            t: { es: 'Finance, que es todo integración', en: 'Finance, which is integration all the way down' },
            d: { es: 'Banco, facturas, gastos y documentos en una sola pantalla. Eso por debajo son conexiones, y se puede abrir y mirar.',
                 en: 'Bank, invoices, expenses and documents on one screen. Underneath, that is connections, and you can open it and look.' } },
  },
  {
    id: 'webs', slug: 'paginas-web',
    precio: 'g-webs', fig: 'webs',
    t: { es: 'Páginas web', en: 'Websites' },
    h: { es: 'Una web que habla con tus sistemas, no un folleto.',
         en: 'A site that talks to your systems, not a brochure.' },
    lead: { es: 'Hacemos la tuya, rehacemos la que tienes o conectamos la que ya funciona. Lo que cambia respecto a una web normal: el formulario entra en tu CRM ya clasificado, la cita cae en la agenda y el stock sale del almacén.',
            en: 'We build yours, rebuild the one you have or connect the one that already works. What changes compared with an ordinary site: the form lands in your CRM already sorted, the booking drops into the diary and stock comes from the warehouse.' },
    puntos: {
      es: [['Diseño propio', 'No una plantilla comprada con tu logo encima. Se nota, y lo nota quien entra.'],
           ['Rápida de verdad', 'Medida, no «nos parece que va bien». Y bien en un teléfono, que es por donde entra la mayoría.'],
           ['Conectada', 'Al CRM, a la agenda, al almacén o a lo que tengas. Con chatbot si lo quieres.'],
           ['A tu nombre', 'Dominio, hosting y accesos. Si un día te vas, te llevas la web.']],
      en: [['Its own design', 'Not a bought template with your logo on it. It shows, and visitors notice.'],
           ['Genuinely fast', 'Measured, not “we think it feels fine”. And right on a phone, which is where most people arrive.'],
           ['Connected', 'To the CRM, the diary, the warehouse or whatever you have. With a chatbot if you want one.'],
           ['In your name', 'Domain, hosting and access. If you leave one day, you take the site with you.']],
    },
    demo: { tipo: 'webs',
            t: { es: 'Cuatro ejemplos, y se pueden bajar', en: 'Four examples, and you can scroll them' },
            d: { es: 'Maquetas nuestras, empresas inventadas. Arrastra dentro de cada una para ver el resto de la página.',
                 en: 'Our own mock-ups, made-up companies. Drag inside each one to see the rest of the page.' } },
  },
];
